version: "3.9"
services:
  dashboard:
    build: .
  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - dashboard
    volumes:
      - ./docker/proxy_params:/etc/nginx/proxy_params
      - ./docker/dashboard.nginx:/etc/nginx/conf.d/default.conf
      - ./dashboard/static:/usr/share/nginx/html/static
